from decimal import Decimal
from typing import Literal, Tuple

from pymath.geometry.d2.circle import Circle
from pymath.geometry.d2.line import Line
from pymath.geometry.d2.point import Point
from pymath.geometry.d2.ray import Ray
from pymath.geometry.d2.segment import Segment


def sgn(d: Decimal) -> Literal[-1, 1]: ...

# intersect ?
def segment_intsersect_segment(segment1: 'Segment', segment2: 'Segment') -> bool: ...

def ray_intersect_segment(ray: 'Ray', segment) -> bool: ...

def ray_intersect_ray(ray1: 'Ray', ray2: 'Ray') -> bool: ...

def line_intersect_segment(line: 'Line', segment: 'Segment') -> bool: ...

def line_intersect_ray(line: 'Line', ray: 'Ray') -> bool: ...

def line_intersect_line(line1: 'Line', line2: 'Line') -> bool: ...

def circle_intersect_segment(circle: 'Circle', segment: 'Segment') -> bool: ...

def circle_intersect_ray(circle: 'Circle', ray: 'Ray') -> bool: ...

def circle_intersect_line(circle: 'Circle', line: 'Line') -> bool: ...

def circle_intersect_circle(circle1: 'Circle', circle2: 'Circle') -> bool: ...

# get number of intersections
def count_cicle_inter_segment(circle: 'Circle', segment: 'Segment') -> Decimal: ...

def count_cicle_inter_ray(circle: 'Circle', ray: 'Ray') -> Decimal: ...

def count_cicle_inter_line(circle: 'Circle', line: 'Line') -> Decimal: ...

def count_cicle_inter_circle(circle1: 'Circle', circle2: 'Circle') -> Decimal: ...

# get intersection
def get_segment_inter_segment(segment1: 'Segment', segment2: 'Segment') -> None | 'Point' |'Segment': ...
    
def get_ray_inter_segment(ray: 'Ray', segment: 'Segment') -> None | 'Point' | 'Segment': ...

def get_ray_inter_ray(ray1: 'Ray', ray2: 'Ray') -> None | 'Point' | 'Ray': ...

def get_line_inter_segment(line: 'Line', segment: 'Segment') -> None | 'Point' |'Segment': ...

def get_line_inter_ray(line: 'Line', ray: 'Ray') -> None | 'Point' | 'Ray': ...

def get_line_inter_line(line1: 'Line', line2: 'Line') -> None | 'Point' | 'Line': ...

def get_circle_inter_segment(circle: 'Circle', segment: 'Segment') -> None | 'Point' | Tuple['Point', 'Point']: ...

def get_circle_inter_ray(circle: 'Circle', ray: 'Ray') -> None | 'Point' | Tuple['Point', 'Point']: ...

def get_circle_inter_line(circle: 'Circle', line: 'Line') -> None | 'Point' | Tuple['Point', 'Point']: ...

def get_circle_inter_circle(circle1: 'Circle', circle2: 'Circle') -> None | 'Point' | Tuple['Point', 'Point'] | 'Circle': ...
