from pymath.geometry.d2.line import Line
from pymath.geometry.d2.point import Point
from pymath.geometry.d2.segment import Segment


# intersect ?
def line_intersect_line(line1: 'Line', line2: 'Line') -> bool: ...

def line_intersect_segment(line: 'Line', segment: 'Segment') -> bool: ...
    
def segment_intsersect_segment(segment1: 'Segment', segment2: 'Segment') -> bool: ...

# get intersection
def get_line_inter_line(line1: 'Line', line2: 'Line') -> None | 'Point' | 'Line': ...
    
def get_line_inter_segment(line: 'Line', segment: 'Segment') -> None | 'Point' |'Segment': ...
    
def get_segment_inter_segment(segment1: 'Segment', segment2: 'Segment') -> None | 'Point' |'Segment': ...
